amazon-braket/amazon-braket-containers

- README.md
- pytorch/jobs/docker/1.8/py3/Dockerfile.cpu
- tensorflow/jobs/docker/2.4/py3/Dockerfile.cpu
Issue #, if available:
Description of changes:
change: Update Pennylane to 0.20.0 and correction to README
Deployed to a personal account and validated successful container creation. Tested following the steps outlined in the README.
> change: Update Pennylane to 0.20.0 and correction to README

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/1.8/py3/Dockerfile.cpu
- tensorflow/jobs/docker/2.4/py3/Dockerfile.cpu
change: OQC schemas and SDK updates included in containers
> change: OQC schemas and SDK updates included in containers

- pytorch/jobs/docker/1.8/py3/Dockerfile.cpu
- tensorflow/jobs/docker/2.4/py3/Dockerfile.cpu
fix: Run a apt-get update to ~/apts/lists
Running an `apt-get update` before pulling in the packages to unblock existing builds. Later work for a py2 upgrade is needed.
> fix: Run a apt-get update to ~/apts/lists

- README.md
fix: Add instructions for other frameworks
> fix: Add instructions for other frameworks

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/buildspec.yml
- pytorch/jobs/docker/1.9/py3/Dockerfile.gpu
- src/constants.py
- tensorflow/buildspec.yml
- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
Change to GPU dockerfiles for pytorch and tensorflow
> change: Change to GPU dockerfiles for pytorch and tensorflow

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/1.9/py3/Dockerfile.gpu
change: Update SDK to the latest version
> change: Update SDK to the latest version

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/1.9/py3/Dockerfile.gpu
- src/requirements.txt
- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
- test/requirements.txt
fix: Raise all boto and awscli versions
> fix: Raise all boto and awscli versions

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/1.9/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
> update: bumping sdk version.

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/1.9/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
> trying to fix tensorflow issues.

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/1.9/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
Upgrade braket sdk
local integration tests and testing examples with BYOC
> feature: update braket SDK for cost tracking

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/1.9/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
- Pinning the pennylane lightning versions
- Adding pennylane-lightning gpu in all images. 
> change: pin pennylane-lightning

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
- Removing pennylane-lightning gpu from the TF and Base images due to conflicts. 
> change: remove lightning-gpu from TF and Base

- tensorflow/buildspec.yml
fix: Raise the tensorflow base container size limit
> fix: Raise the tensorflow base container size limit

- src/braket_container.py
- test/unit_tests/test_braket_container.py
Searches the customer code for a requirements.txt and uses that file as the input to pip install before running customer code.
Was able to have code that relied on a library that was not included in the base container and, by providing a requirements.txt with that library, the code was able to run successfully.
> feature: support requirements.txt to install additional requirements.

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/1.9/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
Bump sdk version to latest release
Validated BDK version, validating with byoc
> feature: bump sdk version

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/1.9/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
Update library versions to support native gates launch
Manual verification of new functionality in all three containers.
> feature: upgrade libraries for native gates launch

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/1.9/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
> feature: Update dependencies for pulse control

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/1.9/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
> Update numpy to 1.21.6

- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
> fix: Update type extensions to 4.3.0

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/1.9/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
> feature: upgrading containers to include latest sdk with AHS features.

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/1.9/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
* Remove ocean libs
* Update libraries to match notebook environment
> fix: remove ocean and dependencies

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/1.9/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
Update adjoint gradient dependencies for containers. 
> fix: update adjoint gradient dependencies

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/1.9/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
updating pl-plugin minor version as per release.
> fix: update pennylane-plugin version

- .github/workflows/python-package.yml
> update: adding build for python 3.10

- .github/workflows/python-package.yml
- README.md
https://github.com/badges/shields/issues/8671
https://github.com/aws-samples/amazon-braket-algorithm-library/commit/40bf548380c56ce4fa95f88e5071ca532a677701
> infra: update github workflows for node12 retirement

- base/buildspec.yml
> fix: update ubuntu version in image tag

- README.md
- base/buildspec.yml
- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/buildspec.yml
- pytorch/jobs/docker/1.9/py3/Dockerfile.gpu
- src/requirements.txt
- tensorflow/buildspec.yml
- tensorflow/jobs/docker/2.4/py3/Dockerfile.gpu
- test/requirements.txt
> feat: upgrade all containers to python 3.9

- README.md
docs: add a support section with relevant links
> docs: add a support section with relevant links

- test/resources/qaoa_utils.py
fix: use the legacy SGD optimizer
See https://github.com/tensorflow/tensorflow/releases/tag/v2.11.0-rc0 for details on the backwards incompatible changes.
> fix: use the legacy SGD optimizer

- base/buildspec.yml
- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/buildspec.yml
- pytorch/jobs/docker/2.0/py3/Dockerfile.gpu
- tensorflow/buildspec.yml
- tensorflow/jobs/docker/2.12/py3/Dockerfile.gpu
> feat: support python 3.10 version of container images

- pytorch/jobs/docker/2.0/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.12/py3/Dockerfile.gpu
> fix: bump version for openfermion to 1.5.1 for Pytorch and Tensorflow containers

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/2.0/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.12/py3/Dockerfile.gpu
> fix: explicitly update vim for each of the images

- pytorch/jobs/docker/2.0/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.12/py3/Dockerfile.gpu
> fix: update cuquantum for Tensorflow and Pytorch repos

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/2.0/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.12/py3/Dockerfile.gpu
> feat: Upgrade to Pennylane 0.30.0

- README.md
- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/2.0/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.12/py3/Dockerfile.gpu
> feat: Introduce error mitigation

- test/requirements.txt
See https://github.com/aws/amazon-braket-examples/commit/8151f949bd06c04d626e96b49abdd522a495e4f1 for more context. 
TLDR; PyYAML needs to be updated through a dependency upgrade for boto
> fix: update boto3 version

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/2.0/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.12/py3/Dockerfile.gpu
> feat: update braket dependencies

- src/requirements.txt
- test/requirements.txt
pins the certifi dependency in requirements file. 
verified after pushing an image locally. 
> fix: pin certifi dependency

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/2.0/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.12/py3/Dockerfile.gpu
Upgrading braket and PL dependencies. 
pushed pytorch image, ran unit-tests
> infra: update braket dependencies

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/2.0/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.12/py3/Dockerfile.gpu
update sdk for aria2
unit-tests
> feat: update sdk for aria2

- pytorch/buildspec.yml
- pytorch/jobs/docker/2.0/py3/Dockerfile.gpu
Local build and unit and integ tests
> feat: upgrade pytorch to 2.0.1

- .github/dependabot.yml
> infra: change the dependabot commit message prefix to infra

- tensorflow/buildspec.yml
- tensorflow/jobs/docker/2.13/py3/Dockerfile.gpu
Upgrade the TF version as well as the BDK and Pennylane.
Tested using the newly made image.
```
python3 -m  pytest test/braket_tests/tensorflow --role service-role/AmazonBraketJobsExecutionRole --tag 2.13.0-gpu-py310-cu118-ubuntu20.04-2023-09-22-11-54-56 --repository braket-base-jobs --region us-west-2
============================================================================================================================ test session starts ============================================================================================================================
platform darwin -- Python 3.11.4, pytest-7.2.2, pluggy-1.3.0
rootdir: /Volumes/Unix/workplace/Braket/braket/amazon-braket-containers
plugins: anyio-3.5.0, …
```
> feat: upgrade tensorflow to 2.13

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/2.0/py3/Dockerfile.gpu
- src/requirements.txt
- tensorflow/jobs/docker/2.13/py3/Dockerfile.gpu
- test/requirements.txt
> feat: dependency updates for queue visibility

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- pytorch/jobs/docker/2.0/py3/Dockerfile.gpu
- tensorflow/jobs/docker/2.13/py3/Dockerfile.gpu
> feat: upgrade bdk version for job helpers

- tensorflow/buildspec.yml
> fix: requirements file path for tensorflow

- test/braket_tests/base/test_jobs_qaoa.py
- test/braket_tests/pytorch/test_jobs_qaoa.py
- test/braket_tests/tensorflow/test_jobs_qaoa.py
- test/resources/qaoa_entry_point.py
We are adding some test metrics so we can track how long the jobs take to start up, and the tests take to run, over time. 
> update: adding test metrics

- base/jobs/docker/1.0/py3/requirements.txt
- pytorch/jobs/docker/2.0/py3/requirements.txt
- tensorflow/jobs/docker/2.13/py3/requirements.txt
This will enable reservations for Braket Direct
> Update Braket libraries

- .github/workflows/build-py-reqs.yml
> feat: add a workflow to build the requirements files

- .github/dependabot.yml
Dependabot has a depth of 1 subdirectory so this fixes the requirements file at deeper depths.
> infra: allow dependabot to find requirement files at deeper depths

- tensorflow/jobs/docker/2.13/py3/requirements.txt
This is breaking our pipeline. I'm reverting back to TF2.12 until we have a more thought out approach to moving to 3.
> fix: reverting tf back to 2.12

- base/jobs/docker/1.0/py3/requirements.txt
- pytorch/jobs/docker/2.0/py3/requirements.txt
- tensorflow/jobs/docker/2.13/py3/requirements.txt
> Update Braket packages

- base/jobs/docker/1.0/py3/requirements.txt
- pytorch/jobs/docker/2.1/py3/requirements.txt
- tensorflow/jobs/docker/2.13/py3/requirements.txt
- test/requirements.txt
feat: upgrade to Pennylane 0.35
Built and tested the 3 containers using the new requirements file.
> feat: upgrade to Pennylane 0.35

- base/jobs/docker/1.0/py3/requirements.txt
> feat: Upgrade qiskit-braket-provider to 0.2.0

- .github/workflows/integ-tests.yml
- src/image.py
- src/output.py
- src/tag_image.py
- test/braket_tests/base/test_jobs_qaoa.py
- test/braket_tests/common/braket_jobs_util.py
- test/braket_tests/pytorch/test_jobs_qaoa.py
- test/braket_tests/tensorflow/test_jobs_qaoa.py
- test/conftest.py
- test/resources/qaoa_entry_point.py
With this change, we'll be able to run a local hybrid job in the containers as part of the actions for a pull request or merge to main.
Testing was done by tracking the GitHub actions and making sure they ran successfully. 
> infra: adding integration tests as part of our github actions

- .github/workflows/integ-tests.yml
Checked against https://github.com/amazon-braket/amazon-braket-containers/settings/secrets/actions
> fix: integ test workflow env variables to capital

- .github/workflows/integ-tests.yml
> infra: free up disk space

- pytorch/jobs/docker/2.2/py3/Dockerfile.gpu
> fix: update pytorch to use cuda 12 version of cuQuantum

- README.md
> doc: add testing instructions for configurable args

- README.md
> doc: correct the org for amazon-braket repos

- base/jobs/docker/1.0/py3/requirements.txt
- pytorch/jobs/docker/2.2/py3/requirements.txt
- tensorflow/jobs/docker/2.14/py3/requirements.txt
> infra: update to BDK 1.90.0

- base/jobs/docker/1.0/py3/Dockerfile.cpu
> infra: update to openmpi v5.0

- base/jobs/docker/1.0/py3/Dockerfile.cpu
- src/image.py
> feat: use multistage builds for the base container

- base/buildspec.yml
- base/jobs/docker/1.0/py3/.dockerignore
- base/jobs/docker/1.0/py3/Dockerfile.cpu
> infra: add a dockerignore file

- buildspec.yml
- Fix no auth permissions issue while creating cuda image 
> infra: add required permission for cudaq image push
